---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Extract artifact
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: Executing node
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
