---
- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Extract artifact
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
